// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyHouse.Infrastructure.Persistence;

#nullable disable

namespace StrategyHouse.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614224738_AddMembersSubmittedAt")]
    partial class AddMembersSubmittedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.ChatbotConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AskedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedIntent")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AskedAt");

                    b.ToTable("ChatbotConversations");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.ContributionPledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContributionKind")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ContributionPledges");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Department", b =>
                {
                    b.Property<string>("DeptCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Dept_Code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Is_Active");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Level");

                    b.Property<string>("NameAr")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name_Ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name_En");

                    b.Property<string>("ParentSector")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Parent_Sector");

                    b.HasKey("DeptCode");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.DepartmentAccessCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("DepartmentAccessCodes");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.DepartmentRoster", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefaultAttending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.HasIndex("DeptCode", "IsActive");

                    b.ToTable("DepartmentRoster");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.DepartmentStrategyMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentsText")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapLayoutJson")
                        .HasColumnType("longtext");

                    b.Property<string>("OpinionsText")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PdfBlob")
                        .HasColumnType("longblob");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WishesText")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("DepartmentStrategyMaps");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Initiative", b =>
                {
                    b.Property<string>("InitiativeCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Initiative_Code");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Budget");

                    b.Property<DateTime?>("EndDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("End_Dates");

                    b.Property<string>("InitiativeName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Initiative_Name");

                    b.Property<decimal?>("Liquidity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity");

                    b.Property<string>("ObjectiveCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Objective_Code");

                    b.Property<string>("ObjectiveName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Objective_Name");

                    b.Property<string>("Owners")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Owners");

                    b.Property<DateTime?>("StartDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("Start_Dates");

                    b.HasKey("InitiativeCode");

                    b.HasIndex("ObjectiveCode");

                    b.ToTable("Initiatives");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Kpi", b =>
                {
                    b.Property<string>("KpiCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("KPI_Code");

                    b.Property<string>("ActivationStatus")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Activation_Status");

                    b.Property<string>("AutomationStatus")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Automation_Status");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Department_Code");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Direction");

                    b.Property<string>("Division")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Division");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Frequency");

                    b.Property<string>("IndexWeight")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("Index_Weight");

                    b.Property<string>("KpiName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("KPI_Name");

                    b.Property<string>("KpiType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("KPI_Type");

                    b.Property<decimal?>("Maximum")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Maximum");

                    b.Property<decimal?>("Minimum")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Minimum");

                    b.Property<string>("ObjectiveCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Objective_Code");

                    b.Property<string>("PlrCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("PLR_Code");

                    b.Property<string>("Target2025")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Target_2025");

                    b.Property<string>("Target2026")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Target_2026");

                    b.Property<string>("Target2027")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Target_2027");

                    b.Property<string>("Target2028")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Target_2028");

                    b.Property<string>("Target2029")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Target_2029");

                    b.Property<string>("Target2030")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Target_2030");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Unit");

                    b.HasKey("KpiCode");

                    b.HasIndex("ObjectiveCode");

                    b.HasIndex("PlrCode");

                    b.ToTable("KPIs");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.MapInkAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeratedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModerationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PngBlob")
                        .HasColumnType("longblob");

                    b.Property<string>("StrokesJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("MemberId");

                    b.ToTable("MapInkAssets");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.ModerationAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModerationAuditLogs");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Objective", b =>
                {
                    b.Property<string>("ObjectiveCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Objective_Code");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Budget");

                    b.Property<DateTime?>("EndDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("End_Dates");

                    b.Property<decimal?>("Liquidity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity");

                    b.Property<string>("ObjPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Obj_Period");

                    b.Property<string>("ObjectiveName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Objective_Name");

                    b.Property<string>("PlrCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("PLR_Code");

                    b.Property<DateTime?>("StartDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("Start_Dates");

                    b.HasKey("ObjectiveCode");

                    b.HasIndex("PlrCode");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Pillar", b =>
                {
                    b.Property<string>("PlrCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("PLR_Code");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Budget");

                    b.Property<DateTime?>("EndDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("End_Dates");

                    b.Property<decimal?>("Liquidity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity");

                    b.Property<string>("PillarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("PILLAR_Name");

                    b.Property<string>("PlrPeriods")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("PLR_Periods");

                    b.Property<DateTime?>("StartDates")
                        .HasColumnType("TEXT")
                        .HasColumnName("Start_Dates");

                    b.HasKey("PlrCode");

                    b.ToTable("Pillars");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Project", b =>
                {
                    b.Property<string>("ProjectCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Project_Code");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Budget");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Department_Code");

                    b.Property<string>("Division")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Division");

                    b.Property<decimal?>("GacBudget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GAC_Budget");

                    b.Property<string>("InitiativeCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Initiative_Code");

                    b.Property<decimal?>("Liquidity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity");

                    b.Property<decimal?>("Liquidity2025")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity_2025");

                    b.Property<decimal?>("Liquidity2026")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity_2026");

                    b.Property<decimal?>("Liquidity2027")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity_2027");

                    b.Property<decimal?>("Liquidity2028")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity_2028");

                    b.Property<decimal?>("Liquidity2029")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity_2029");

                    b.Property<decimal?>("Liquidity2030")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity_2030");

                    b.Property<decimal?>("Liquidity2031")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Liquidity_2031");

                    b.Property<string>("PlrCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("PLR_Code");

                    b.Property<string>("ProjectManager")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Project_Manager");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Project_Name");

                    b.Property<string>("ProjectPhase")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Project_Phase");

                    b.Property<string>("ProjectSponsor")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Project_Sponsor");

                    b.Property<string>("ProjectStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Project_Status");

                    b.Property<string>("ProjectType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Project_Type");

                    b.HasKey("ProjectCode");

                    b.HasIndex("InitiativeCode");

                    b.HasIndex("PlrCode");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCodeFilter")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExplanationAr")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "IsApproved", "IsActive");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.SessionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypedSignature")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionMembers");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.StrategySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessCodeUsed")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MembersSubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrategySessions");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OpensAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientFingerprint")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespondentRole")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyResponses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrategyHouse.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.ContributionPledge", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.StrategySession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.DepartmentStrategyMap", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.StrategySession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Initiative", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.Objective", "Objective")
                        .WithMany("Initiatives")
                        .HasForeignKey("ObjectiveCode");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Kpi", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.Objective", "Objective")
                        .WithMany("Kpis")
                        .HasForeignKey("ObjectiveCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StrategyHouse.Domain.Entities.Pillar", "Pillar")
                        .WithMany("Kpis")
                        .HasForeignKey("PlrCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Objective");

                    b.Navigation("Pillar");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.MapInkAsset", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.DepartmentStrategyMap", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Objective", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.Pillar", "Pillar")
                        .WithMany("Objectives")
                        .HasForeignKey("PlrCode");

                    b.Navigation("Pillar");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Project", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Projects")
                        .HasForeignKey("InitiativeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StrategyHouse.Domain.Entities.Pillar", "Pillar")
                        .WithMany("Projects")
                        .HasForeignKey("PlrCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Initiative");

                    b.Navigation("Pillar");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.SessionMember", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.StrategySession", "Session")
                        .WithMany("Members")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.SurveyResponse", b =>
                {
                    b.HasOne("StrategyHouse.Domain.Entities.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Objective", b =>
                {
                    b.Navigation("Initiatives");

                    b.Navigation("Kpis");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Pillar", b =>
                {
                    b.Navigation("Kpis");

                    b.Navigation("Objectives");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.StrategySession", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("StrategyHouse.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
